config/routes.rb
MyWords::Application.routes.draw do

  resources :notes
  get '/quotes' => 'notes#quotes', as: :notes_quotes

  devise_for :users
  match '/heartbeat' => 'application#heartbeat', :via => :get

  get 'words/define' => 'words#define', as: :define

  get 'users/:id/words' => 'words#index', as: :user_words

  post 'texts' => 'texts#create'

  resources :words, except: [:update, :edit] do
    resources :definitions, only: [:update, :create, :destroy, :edit]
  end

  resources :emails, :only => [:new, :create]

  root 'words#index'
end

app/models/word.rb
class Word < ApplicationRecord
  has_many :definitions, dependent: :destroy
  belongs_to :user
  validates_presence_of :user_id

  def first_definition
    definitions.length > 0 ? definitions.first.text : ""
  end

  def serializable_hash(options={})
    { text => definitions.map(&:text) }
  end

  def self.find_or_create_with_definitions(user, text)
    existing = Word.where(text: text, user: user).first
    return existing if existing

    definitions = Wordnik.word.get_definitions(text).map { |r| r["text"] }
    return nil if definitions.length == 0

    word = Word.create! text: text, user: user
    definitions.each { |d| word.definitions.create! text: d }

    word
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :destroy]
  before_action :authenticate!, only: [:create, :destroy]

  # GET /words
  def index
    if params[:user_id].present?
      @words = Word.where(user_id: params[:user_id])
      @user = User.find(params[:user_id])
    elsif signed_in?
      @words = current_user.words
      @user = current_user
    else
      @words = User.default_user.words
      @user = User.default_user
    end

    respond_to do |format|
      format.html
      format.json { render json: @words }
    end
  end

  # GET /words/1
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # POST /words
  def create
    @word = Word.find_or_create_with_definitions(current_user, params[:word])

    if @word
      respond_to do |format|
        format.html { redirect_to @word, notice: "#{@word.text} was successfully created." }
        format.json { render json: @word }
      end
    else
      error = "No definition found for '#{params[:word]}'"
      respond_to do |format|
        format.html { redirect_to new_word_path, alert: error }
        format.json { render json: { errors: [error] }, status: 422 }
      end
    end
  end

  # DELETE /words/1
  def destroy
    @word.destroy
    redirect_to words_url, notice: "#{@word.text} was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def word_params
      params.require(:word).permit(:text)
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :word %><br>
    <%= text_field_tag :word %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/index.html.erb
<h1>
  <%=t '.title', :default => "Words for user #{@user.id} (#{@words.length})" %>
</h1>

<%= link_to "New", new_word_path, :id => "new_button" %>

<ul id="list_wrapper">
  <% @words.each do |word| %>
    <li>
      <div class="list_links">
        <%= button_to "delete", word, :class => "delete", :method => "delete" %>
      </div>

    <div class="word_header">
      <%= link_to word.text, word_path(word) %>
    </div>
    <%= word.first_definition %>
    </li>
  <% end %>
</ul>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<h1><%= @word.text %> ( <%= @word.definitions.length %> )</h1>

<ul id="list_wrapper">
  <% @word.definitions.each do |definition| %>
    <li>
      <div class="list_links">
        <%= link_to "edit", edit_word_definition_path(@word, definition) %>
        <%= button_to "delete", word_definition_path(@word, definition), :method => "delete" %>
      </div>

      <%= definition.text %>
    </li>
  <% end %>
</ul>