config/routes.rb
MyWords::Application.routes.draw do

  resources :notes
  get '/quotes' => 'notes#quotes', as: :notes_quotes

  devise_for :users
  match '/heartbeat' => 'application#heartbeat', :via => :get

  get 'words/define' => 'words#define', as: :define

  get 'users/:id/words' => 'words#index', as: :user_words

  post 'texts' => 'texts#create'

  resources :words, except: [:update, :edit] do
    resources :definitions, only: [:update, :create, :destroy, :edit]
  end

  resources :emails, :only => [:new, :create]

  root 'words#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MyWords" %></title>
    <%= csrf_meta_tags %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.png', skip_pipeline: true, rel: 'shortcut icon' %>
    <%= stylesheet_link_tag "application", :media => "all" %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div id="container-main">
      <div id="navbar">
        <ul>
          <li>
            <%= link_to "MyWords", "/" %>
          </li>

          <% if user_signed_in? %>
            <li>
              <%= link_to "Notes", notes_path %>
            </li>
            <li>
              <%= link_to "Quotes", notes_quotes_path %>
            </li>
            <li>
              <%= link_to current_user.email, edit_user_registration_path(current_user) %>
            </li>
            <li>
              <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Login', new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div><!-- /navbar -->

      <ul id="flash">
        <% flash.each do |k, v| %>
          <li class="<%= k %>"><%= v %></li>
        <% end %>
      </ul>

      <div id="content">
        <%= yield %>
      </div>
    </div><!-- /container -->

  </body>
</html>